// Sync logic: parse agentus.yaml, generate channel names, build sync plans,
// generate legacy agents.yaml. Pure functions — no Discord API calls.

import yaml from "js-yaml";
import { randomUUID } from "crypto";

const CLAUDE_CMD = "claude --continue --dangerously-skip-permissions";

/** Expand ~ to $HOME in paths */
export function expandTilde(p) {
  if (p.startsWith("~/")) return p.replace("~", process.env.HOME);
  return p;
}

/**
 * Parse agentus.yaml content into normalized config.
 * @returns {{ guild: string, category: string, agents: Map<string, { dir, claude, services, shells, layout }> }}
 */
export function parseAgentusConfig(yamlContent) {
  const doc = yaml.load(yamlContent);
  if (!doc?.guild) throw new Error("agentus.yaml: 'guild' is required");
  if (!doc?.agents || typeof doc.agents !== "object") throw new Error("agentus.yaml: 'agents' section is required");

  const agents = new Map();
  for (const [name, config] of Object.entries(doc.agents)) {
    if (!config?.dir) throw new Error(`agentus.yaml: agent '${name}' needs a 'dir'`);
    agents.set(name, {
      dir: expandTilde(config.dir),
      claude: config.claude ?? 1,
      services: config.services ?? [],
      shells: config.shells ?? 0,
      layout: config.layout ?? (config.services?.length || config.shells ? "main-vertical" : undefined),
    });
  }

  return {
    guild: String(doc.guild),
    category: doc.category || "Agents",
    agents,
  };
}

/**
 * Generate Discord channel names from agent config.
 * Returns a flat, alphabetically sorted list of { agentName, channelName, pane }.
 * Naming: #agent (pane 0), #agent-2 (pane 1), #agent-3 (pane 2).
 */
export function generateChannelNames(agents) {
  const result = [];
  const sortedNames = [...agents.keys()].sort();

  for (const name of sortedNames) {
    const { claude } = agents.get(name);
    for (let i = 0; i < claude; i++) {
      result.push({
        agentName: name,
        channelName: i === 0 ? name : `${name}-${i + 1}`,
        pane: i,
      });
    }
  }
  return result;
}

/**
 * Build a sync plan by comparing desired channels with existing Discord channels.
 * @param {Array<{ agentName, channelName, pane }>} desired
 * @param {Array<{ name: string, id: string }>} existing - channels in the target category
 * @returns {{ toCreate: Array, existing: Array, orphaned: Array }}
 */
export function buildSyncPlan(desired, existing) {
  const existingByName = new Map(existing.map((ch) => [ch.name.toLowerCase(), ch]));
  const desiredNames = new Set(desired.map((d) => d.channelName.toLowerCase()));

  const toCreate = [];
  const matched = [];

  for (const d of desired) {
    const found = existingByName.get(d.channelName.toLowerCase());
    if (found) {
      matched.push({ ...d, id: found.id });
    } else {
      toCreate.push(d);
    }
  }

  const orphaned = existing.filter((ch) => !desiredNames.has(ch.name.toLowerCase()));

  return { toCreate, existing: matched, orphaned };
}

/**
 * Generate legacy agents.yaml content for backward compat with `agent` CLI.
 * @param {Map<string, object>} agents - parsed agent configs
 * @param {Map<string, string>} channelMap - channelName → channelId
 * @param {Map<string, string>} agentIds - agentName → UUID
 */
export function generateAgentsYaml(agents, channelMap, agentIds) {
  const result = {};
  const sortedNames = [...agents.keys()].sort();

  for (const name of sortedNames) {
    const config = agents.get(name);
    const entry = {
      dir: config.dir,
      id: agentIds.get(name) || randomUUID(),
    };

    // Discord channel mapping (only claude panes)
    const discord = {};
    for (let i = 0; i < config.claude; i++) {
      const channelName = i === 0 ? name : `${name}-${i + 1}`;
      const channelId = channelMap.get(channelName);
      if (channelId) discord[channelId] = i;
    }
    if (Object.keys(discord).length) entry.discord = discord;

    // Layout
    if (config.layout) entry.layout = config.layout;

    // Panes: claude first, then services, then shells
    const panes = [];
    for (let i = 0; i < config.claude; i++) {
      const pane = { name: i === 0 ? "claude" : `claude-${i + 1}`, cmd: CLAUDE_CMD };
      panes.push(pane);
    }
    for (let i = 0; i < config.services.length; i++) {
      panes.push({ name: `service-${i + 1}`, cmd: config.services[i] });
    }
    for (let i = 0; i < config.shells; i++) {
      panes.push({ name: `shell-${i + 1}`, cmd: "bash" });
    }
    entry.panes = panes;

    result[name] = entry;
  }

  return "# Auto-generated by Agentus /sync — do not edit manually\n" + yaml.dump(result, { lineWidth: -1, quotingType: '"' });
}
