import type { ProductEmitterPlugin, ProductIr } from "@v1d/product-spec";
import type { AgentmuxLinkProductIr } from "./product.js";

export function linkKotlinEmitter(path: string): ProductEmitterPlugin {
  return {
    id: "link-kotlin",
    emit(product) {
      const link = requireLinkProduct(product);
      return [{ id: "link-kotlin", path, mediaType: "text/x-kotlin", content: emitKotlin(link) }];
    },
  };
}

function requireLinkProduct(product: ProductIr): AgentmuxLinkProductIr {
  if (product.id !== "agentmux-link" || !("link" in product)) {
    throw new Error("Link Kotlin emitter received another product");
  }
  return product as AgentmuxLinkProductIr;
}

function emitKotlin(product: AgentmuxLinkProductIr): string {
  const profiles = product.link.artifacts.map((item) =>
    `    ${enumName(item.id)}(${str(item.id)}, setOf(${item.surfaces.map(str).join(", ")})),`).join("\n");
  const routes = product.link.routes.map((item) =>
    `    ${enumName(item.id)}(${str(item.id)}),`).join("\n");
  const actions = product.link.menuActions.map((item) =>
    `    ${enumName(item.id)}(${str(item.id)}),`).join("\n");
  const componentIds = product.link.components.map((item) =>
    `    ${enumName(item.id)}(${str(item.id)}),`).join("\n");
  const routeDescriptors = product.link.routes.map((item) =>
    `        LinkRouteDescriptor(LinkRoute.${enumName(item.id)}, ${str(item.title)}, ${str(item.iconId)}, setOf(${item.artifacts.map((id) => `LinkArtifactProfile.${enumName(id)}`).join(", ")})),`).join("\n");
  const actionDescriptors = product.link.menuActions.map((item) =>
    `        LinkMenuActionDescriptor(LinkMenuAction.${enumName(item.id)}, ${str(item.rowId)}, ${str(item.title)}, ${str(item.detail)}, ${str(item.a11y)}, ${str(item.iconId)}, LinkRoute.${enumName(item.destination)}, setOf(${item.artifacts.map((id) => `LinkArtifactProfile.${enumName(id)}`).join(", ")})),`).join("\n");
  const components = product.link.components.map((item) =>
    `        LinkComponentDescriptor(LinkComponentId.${enumName(item.id)}, ${str(item.rendererId)}, ${str(item.iconId)}, setOf(${item.artifacts.map((id) => `LinkArtifactProfile.${enumName(id)}`).join(", ")})),`).join("\n");
  const trees = product.componentFamilies.flatMap(({ screen, family }) =>
    family.trees.map((tree) => {
      const mounts = tree.mounts.map((item) =>
        `LinkComponentMount(LinkComponentId.${enumName(item.component)}, ${str(item.region)}, ${item.order}, ${item.requirement.kind === "optional"})`).join(", ");
      return `        LinkComponentTree(LinkRoute.${enumName(screen)}, ${str(tree.surface)}, listOf(${mounts})),`;
    })).join("\n");
  const palettes = product.link.palettes.map((item) =>
    `        LinkPaletteDescriptor(${str(item.id)}, setOf(${item.artifacts.map((id) => `LinkArtifactProfile.${enumName(id)}`).join(", ")})),`).join("\n");
  const services = product.legos.mounts.map((item) => {
    const inputs = item.lego.inputs.map(({ id }) => str(id)).join(", ");
    const outputs = item.lego.outputs.map(({ id }) => str(id)).join(", ");
    const runtime = item.lego.runtime;
    return `        LinkServiceDescriptor(${str(item.id)}, listOf(${inputs}), listOf(${outputs}), ${str(runtime.stateOwner)}, ${str(runtime.lifetime)}, ${str(runtime.durability)}, ${str(runtime.clockDomain)}, listOf(${runtime.contextInputs.map(str).join(", ")}), listOf(${runtime.effects.map(str).join(", ")})),`;
  }).join("\n");

  return `// Generated by product-spec/src/generate.ts. Do not edit.
package io.agentmux.linkui.product.generated

enum class LinkArtifactProfile(val id: String, val surfaces: Set<String>) {
${profiles}
}
enum class LinkRoute(val id: String) {
${routes}
}
enum class LinkMenuAction(val id: String) {
${actions}
}
enum class LinkComponentId(val id: String) {
${componentIds}
}
data class LinkRouteDescriptor(val route: LinkRoute, val title: String, val iconId: String, val artifacts: Set<LinkArtifactProfile>)
data class LinkMenuActionDescriptor(val action: LinkMenuAction, val rowId: String, val title: String, val detail: String, val contentDescription: String, val iconId: String, val destination: LinkRoute, val artifacts: Set<LinkArtifactProfile>)
data class LinkComponentDescriptor(val id: LinkComponentId, val rendererId: String, val iconId: String, val artifacts: Set<LinkArtifactProfile>)
data class LinkComponentMount(val component: LinkComponentId, val region: String, val order: Int, val optional: Boolean)
data class LinkComponentTree(val route: LinkRoute, val surface: String, val mounts: List<LinkComponentMount>)
data class LinkPaletteDescriptor(val id: String, val artifacts: Set<LinkArtifactProfile>)
data class LinkServiceDescriptor(val id: String, val inputPorts: List<String>, val outputPorts: List<String>, val stateOwner: String, val lifetime: String, val durability: String, val clockDomain: String, val contextInputs: List<String>, val effects: List<String>)

object LinkProductManifest {
    const val PRODUCT_ID: String = ${str(product.id)}
    const val PRODUCT_SPEC_VERSION: String = ${str(product.productSpecVersion)}
    val routes: List<LinkRouteDescriptor> = listOf(
${routeDescriptors}
    )
    val menuActions: List<LinkMenuActionDescriptor> = listOf(
${actionDescriptors}
    )
    val components: List<LinkComponentDescriptor> = listOf(
${components}
    )
    val componentTrees: List<LinkComponentTree> = listOf(
${trees}
    )
    val palettes: List<LinkPaletteDescriptor> = listOf(
${palettes}
    )
    val services: List<LinkServiceDescriptor> = listOf(
${services}
    )
    fun route(route: LinkRoute): LinkRouteDescriptor = routes.single { it.route == route }
    fun action(action: LinkMenuAction): LinkMenuActionDescriptor = menuActions.single { it.action == action }
    fun component(id: LinkComponentId): LinkComponentDescriptor = components.single { it.id == id }
    fun tree(route: LinkRoute, surface: String): LinkComponentTree = componentTrees.single { it.route == route && it.surface == surface }
}
`;
}

function enumName(id: string): string {
  return id.replaceAll(/[^A-Za-z0-9]+/gu, "_").toUpperCase();
}
function str(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n")}"`;
}
