// Native execution safety for every autonomous agentmux launch path.
//
// Keep policy decisions in the runtime vendors' dedicated reviewers. This
// module is intentionally only the shared launch contract: Claude auto mode
// and Codex's workspace sandbox + auto reviewer. A launcher must never invent
// its own weaker variant of these arguments.

export const CLAUDE_AUTONOMOUS_ARGS = Object.freeze([
  "--permission-mode", "auto",
  "--no-chrome",
]);

export const CODEX_AUTONOMOUS_ARGS = Object.freeze([
  "--sandbox", "workspace-write",
  "--ask-for-approval", "on-request",
  "-c", "sandbox_workspace_write.network_access=true",
  "-c", 'approvals_reviewer="auto_review"',
]);

export const CODEX_APP_SERVER_ARGS = Object.freeze([
  "app-server",
  "-c", "sandbox_workspace_write.network_access=true",
  "-c", 'approvals_reviewer="auto_review"',
  "--stdio",
]);

export const CODEX_AUTONOMOUS_THREAD_POLICY = Object.freeze({
  sandbox: "workspace-write",
  approvalPolicy: "on-request",
  approvalsReviewer: "auto_review",
});

export const CODEX_AUTONOMOUS_TURN_POLICY = Object.freeze({
  sandboxPolicy: Object.freeze({
    type: "workspaceWrite",
    networkAccess: true,
  }),
  approvalPolicy: "on-request",
  approvalsReviewer: "auto_review",
});

// Shell network access stays available for builds, tests and deploys. Direct
// GUI/browser launch commands instead cross an execpolicy approval seam, where
// Codex's auto reviewer can distinguish an explicit user request from an
// untrusted-page instruction. Headless Playwright test runs remain untouched;
// only its interactive browser entry points are escalated.
export const CODEX_EXTERNAL_NAVIGATION_RULES = `# Managed by agentmux. Do not edit this file by hand.
prefix_rule(
    pattern = [[
        "xdg-open", "open", "gio", "gnome-open", "sensible-browser", "x-www-browser",
        "google-chrome", "google-chrome-stable", "chrome", "chromium", "chromium-browser",
        "firefox", "/usr/bin/xdg-open", "/usr/bin/google-chrome", "/usr/bin/chromium",
        "/usr/bin/firefox",
    ]],
    decision = "prompt",
    justification = "External GUI/browser navigation requires reviewer-confirmed user authorization.",
    match = [
        "xdg-open https://example.com",
        "google-chrome https://example.com",
        "firefox https://example.com",
    ],
)

prefix_rule(
    pattern = ["playwright", ["open", "codegen", "show-report"]],
    decision = "prompt",
    justification = "Interactive Playwright navigation requires reviewer-confirmed user authorization.",
    match = ["playwright codegen https://example.com"],
    not_match = ["playwright test"],
)

prefix_rule(
    pattern = ["playwright", "test", ["--ui", "--headed"]],
    decision = "prompt",
    justification = "Interactive Playwright test windows require reviewer-confirmed user authorization.",
    match = ["playwright test --ui"],
)

prefix_rule(
    pattern = [["npx", "pnpm", "yarn"], "playwright", ["open", "codegen", "show-report"]],
    decision = "prompt",
    justification = "Interactive Playwright navigation requires reviewer-confirmed user authorization.",
    match = ["npx playwright codegen https://example.com"],
    not_match = ["npx playwright test"],
)

prefix_rule(
    pattern = [["npx", "pnpm", "yarn"], "playwright", "test", ["--ui", "--headed"]],
    decision = "prompt",
    justification = "Interactive Playwright test windows require reviewer-confirmed user authorization.",
    match = ["npx playwright test --headed"],
)
`;

const SAFE_SHELL_ARG = /^[A-Za-z0-9_./:=+-]+$/;

/** Render fixed argv as a shell fragment without weakening its argument boundaries. */
export function renderShellArgs(args) {
  return args.map((arg) => {
    const value = String(arg);
    if (SAFE_SHELL_ARG.test(value)) return value;
    return `'${value.replaceAll("'", `'\\''`)}'`;
  }).join(" ");
}

export const CLAUDE_AUTONOMOUS_FLAGS = renderShellArgs(CLAUDE_AUTONOMOUS_ARGS);
export const CODEX_AUTONOMOUS_FLAGS = renderShellArgs(CODEX_AUTONOMOUS_ARGS);
