import { unit, feature, expect } from "bdd-vitest";
import { isSystemNoiseDirective } from "./system-noise.mjs";

feature("isSystemNoiseDirective", () => {
  unit("slash-command wrappers are noise", {
    given: ["the live-repro wrapper turns", () => ([
      "<command-name>/compact</command-name>",
      "<local-command-stdout>Compacted</local-command-stdout>",
      "  <command-message>compact</command-message>",
    ])],
    when: ["classifying each", (turns) => turns.map(isSystemNoiseDirective)],
    then: ["every wrapper is noise", (result) => expect(result).toEqual([true, true, true])],
  });

  unit("a bare /compact or /model turn is noise", {
    when: ["classifying bare command turns", () => ([
      isSystemNoiseDirective("/compact"),
      isSystemNoiseDirective("/model"),
      // ...but a sentence MENTIONING /compact is a real directive.
      isSystemNoiseDirective("kör /compact på alla panes över 70%"),
    ])],
    then: ["exact turns are noise, the sentence is not", (result) =>
      expect(result).toEqual([true, true, false])],
  });

  unit("harness banners are noise", {
    when: ["classifying continuation, caveat, hints and system tags", () => ([
      isSystemNoiseDirective("This session is being continued from a previous conversation that ran out of context."),
      isSystemNoiseDirective("Caveat: The messages below were generated by the user while running local commands."),
      isSystemNoiseDirective("[amux resume hint] session jsonl at ..."),
      isSystemNoiseDirective("[AMUX AUTOMATIC QUOTA RECOVERY · SAME CLAUDE SESSION]\nContinue."),
      isSystemNoiseDirective("<system-reminder>background stuff</system-reminder>"),
      isSystemNoiseDirective("[Request interrupted by user]"),
      isSystemNoiseDirective(""),
    ])],
    then: ["all are noise", (result) => expect(result).toEqual([true, true, true, true, true, true, true])],
  });

  unit("real directives are never noise", {
    when: ["classifying human, inter-agent and cron briefs", () => ([
      isSystemNoiseDirective("fixa buggen i login-flödet"),
      isSystemNoiseDirective("[from claw:2] BANKAD för din review: PR #22"),
      isSystemNoiseDirective("[dream 2026-07-15 04:00] Läs filen först: memory/2026-07-15.md"),
    ])],
    then: ["none are noise", (result) => expect(result).toEqual([false, false, false])],
  });
});
